Issues/43 dsf roles
datasharingframework/dsf pull request #44
Opened 2023-06-06 13:29 UTC by wetret

* Adds role `DMS` (Data Management Site)
* Renames role `MeDIC` to `DIC`
* Renames everything from `medic` to `dic`
* Increases version of all FHIR resources to `1.0.0`
* Add version to canonicalUrls in profiles 
* Adds version to ValueSet CodeSystem includes

resolves #43

2023-06-12 16:29 UTC, hhund requested changes
Some minor requests inline.

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
test resource no version change needed, can this file be removed?
```suggestion
	<version value="0.5.0"/>
```

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-extension-certificate-thumbprint-0.5.0.xml
> +	<version value="1.0.0"/>
test resource no version change needed, can this file be removed?
```suggestion
	<version value="0.5.0"/>
```

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-organization-0.5.0.xml
> +	<version value="1.0.0"/>
test resource no version change needed, can this file be removed?
```suggestion
	<version value="0.5.0"/>
```

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-task-0.5.0.xml
> +	<version value="1.0.0"/>
test resource no version change needed, can this file be removed?
```suggestion
	<version value="0.5.0"/>
```

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-validation/src/main/resources/fhir/CodeSystem/dsf-organization-role-1.0.0.xml
>  </CodeSystem>
Please add `UAC`

2023-06-12 16:29 UTC, hhund commented on dsf-fhir/dsf-fhir-validation/src/main/resources/fhir/StructureDefinition/dsf-organization-1.0.0.xml
> +        <targetProfile value="http://dsf.dev/fhir/StructureDefinition/endpoint|1.0.0" />
Does this mean that the referenced Endpoint resource needs to version specific profile declaration?

...other StructureDefinition resources -> same question.

2023-06-13 08:37 UTC, wetret commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
I forgot to rename the file to dsf-endpoint-1.0.0.xml. The file is used for tests, so it should stay. Should I return to `version=0.5.0` and leave it as it was the previous DSF version or should I rename the file and completely adapt the test resources as well to the new DSF version, thereby changing the HiGHmed naming as well to the new DSF naming?

2023-06-13 09:25 UTC, wetret commented on dsf-fhir/dsf-fhir-validation/src/main/resources/fhir/CodeSystem/dsf-organization-role-1.0.0.xml
>  </CodeSystem>
added with 886c4ee4

2023-06-13 09:37 UTC, wetret commented on dsf-fhir/dsf-fhir-validation/src/main/resources/fhir/StructureDefinition/dsf-organization-1.0.0.xml
> +        <targetProfile value="http://dsf.dev/fhir/StructureDefinition/endpoint|1.0.0" />
The validator does not enforce the declaration of the version in the meta.profile tag. My intention was to make it clear, how the profiles are linked with each other in case there are multiple versions of the same profile. Probably it would make sense to add the versions to the specific resources or to remove the version tag in the profiles if there will not be different version of the profile. What do you think?

2023-06-13 09:41 UTC, wetret commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
My intention was to raise all version numbers to `1.0.0` and actually also to replace `HiGHmed` in the file names. I forgot to do this with the test resources. Should the version remain at `0.5.0` or should I also rename the files to `1.0.0` and replace `HiGHmed` with `DSF` in the file names?

2023-06-13 10:20 UTC, hhund commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
If possible, we should delete theses files (incl. DeBasis/...), if not -> 1.0.0/DSF.

2023-06-13 10:22 UTC, hhund commented on dsf-fhir/dsf-fhir-validation/src/main/resources/fhir/StructureDefinition/dsf-organization-1.0.0.xml
> +        <targetProfile value="http://dsf.dev/fhir/StructureDefinition/endpoint|1.0.0" />
Following the documentation intention and since it doesn't break anything, we should keep the version number.

2023-06-13 11:48 UTC, wetret commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
The resources are used for a StructureDefinition [testTree()](https://github.com/datasharingframework/dsf/blob/004edc54b8dbea94688d2846c287ed03ed02a784/dsf-fhir/dsf-fhir-server/src/test/java/dev/dsf/fhir/hapi/StructureDefinitionTreeTest.java#L30). I will therefore rename the files.

2023-06-13 12:21 UTC, wetret commented on dsf-fhir/dsf-fhir-server/src/test/resources/profiles/highmed-endpoint-0.5.0.xml
> +	<version value="1.0.0"/>
resolved with 827300d

2023-06-13 15:26 UTC, hhund approved these changes

2023-06-13 15:40 UTC, merged